#!/usr/bin/env node
// Reads every file in knowledge-base/ and writes them as a single string
// constant to src/lib/knowledge-base.generated.ts. Runs as a prebuild step
// so Vercel always has the latest content baked into the bundle.

import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, relative, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const kbDir = join(repoRoot, 'knowledge-base')
const outFile = join(repoRoot, 'src', 'lib', 'knowledge-base.generated.ts')

function walk(dir) {
  const out = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      out.push(...walk(full))
    } else if (/\.(md|txt)$/i.test(entry)) {
      out.push(full)
    }
  }
  return out.sort()
}

const files = walk(kbDir)
const sections = files.map(file => {
  const content = readFileSync(file, 'utf-8').replace(/^﻿/, '').trim()
  const rel = relative(kbDir, file).replace(/\\/g, '/')
  return `===== ${rel} =====\n${content}`
})

const combined = sections.join('\n\n')

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(
  outFile,
  `// Generated by scripts/bake-kb.mjs — do not edit manually.\n` +
    `// Re-run automatically before build/dev. To force: npm run bake-kb\n\n` +
    `export const KNOWLEDGE_BASE = ${JSON.stringify(combined)}\n`,
)

console.log(`Baked ${files.length} files (${combined.length} chars) -> ${relative(repoRoot, outFile)}`)
